---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cloud-proxy
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: NodePort
  selector:
    app: kafka-cloud-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cloud-proxy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kafka-cloud-proxy
  template:
    metadata:
      labels:
        app: kafka-cloud-proxy
    spec:
      containers:
        - name: kafka-cloud-proxy
          image: confluentinc/cp-kafka-rest:5.1.3
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["kafka-rest-start /etc/kafka-rest-cloud/kafka-rest-config.properties"]
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - name: kafka-rest-config
              mountPath: /etc/kafka-rest-cloud/
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: kafka-rest-config
          secret:
            secretName: kafka-rest-config
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-cloud-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-cloud-proxy
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
